import { CommitDiffSchema } from "@gitbeaker/rest";
import { ChatCompletionMessageParam, ChatCompletion } from "openai/resources/index.mjs";


const QUESTIONS = `\n\nQuestions:\n
1. Can you summarize the changes in a succinct bullet point list\n
2. In the diff, are the added or changed code written in a clear and easy to understand way?\n
3. Does the code use comments, or descriptive function and variables names that explain what they mean?\n
4. based on the code complexity of the changes, could the code be simplified without breaking its functionality? if so can you give example snippets?\n
5. Can you find any bugs, if so please explain and reference line numbers?\n
6. Do you see any code that could induce security issues?\n\n`

const MESSAGES: ChatCompletionMessageParam[] = [{
    role: 'system',
    content: "You are a senior developer reviewing code changes."
},
{
    role: 'assistant',
    content: "Format the response so it renders nicely in GitLab, with nice and organized markdown (use code blocks if needed), and send just the response no comments on the request, when answering include a short version of the question, so we know what it is."
}]

const ERROR_ANSWER = `I'm sorry, I'm not feeling well today. Please ask a human to review this code change.`

const DISCLAIMER = `This comment was generated by an artificial intelligence duck.`

export const buildPrompt = (oldFiles: string[], changes: CommitDiffSchema[]): { messages: ChatCompletionMessageParam[] } => {
    const content = `
    As a senior developer, review the following code changes and answer code review questions about them. The code changes are provided as git diff strings.
    The entire file before the change is provided for context. Make sure to keep it as a reference when reviewing the changes.

    Files before changes:
    ${oldFiles.join('\n\n')}

    Changes:
    ${changes.map(change => change.diff).join('\n\n')}

    ${QUESTIONS}
    `

    const messages: ChatCompletionMessageParam[] = [...MESSAGES, { role: 'user', content }]

    return { messages };
}

export const buildAnswer = (completion: ChatCompletion | Error | undefined): string => {
    let answer: string = '';
    if (!completion) {
        answer = ERROR_ANSWER;
    }
    if (completion instanceof Error) {
        answer = `${ERROR_ANSWER}\n\nError: ${completion.message}`;
    }
    return `${answer}\n\n${DISCLAIMER}`;
}